version: '3.4'
services:
  web:
    build: ./cbpro-trader/web
    volumes:
      - ./cbpro-trader/web/:/app
    ports:
      - "3000:3000"
      - "35729:35729"

  cbpro:
    build: ./cbpro-trader/daemon
    volumes:
      - ./cbpro-trader/daemon/:/cbpro-trader/:Z
    environment:
      - FLASK_RUN_PORT=5000
      - CBPRO_CONFIG=config.yml
