version: '3.4'
services:
  web:
    build: ./web
    volumes:
      - ./web/:/app
    ports:
      - "3000:3000"
      - "35729:35729"

  cbpro:
    build: ./daemon
    volumes:
      - ./daemon/:/app/:Z
    environment:
      - CBPRO_CONFIG=config.yml
      - WEB_PATH=web
    ports:
      - "5000:5000"
